/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.barclays.lar;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;

@EnableEurekaClient
@EnableZuulProxy
@SpringBootApplication
public class GatewayService {
    public String getGreeting() {
        return "Hello GatewayService.";
    }

    public static void main(String[] args) {
        System.out.println(new GatewayService().getGreeting());
        SpringApplication.run(GatewayService.class, args);
    }
}
