/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.barclays.lar;

import org.junit.Test;
import static org.junit.Assert.*;

public class DisclosureAppTest {
    @Test public void testAppHasAGreeting() {
        DisclosureApp classUnderTest = new DisclosureApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
