zuul:
  prefix: /api
  routes:
    certification:
      path: /certification/**
      serviceId: CERTIFICATION
    disclosure:
      path: /disclosure/**
      serviceId:  DISCLOSURE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
server:
  port: 8766
  
spring:
  application:
    name: GATEWAY-SERVICE      